// <auto-generated />
using Lab7_StudentRegistration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab7_StudentRegistration.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    partial class StudentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Lab7_StudentRegistration.Models.StuMajor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stu_ID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Stu_Majors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StuMajors");
                });

            modelBuilder.Entity("Lab7_StudentRegistration.Models.Student", b =>
                {
                    b.Property<string>("Stu_ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stu_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Stu_Passwd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Stu_Prog")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Stu_ID");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
